### ISSUE TITLE
Speedcopy fails to copy files from dropbox folder to network share

### ISSUE THREAD

**Issue by BigRoy** [antirotor/speedcopy#24]
If certain properties can't be transferred to the destination the file _will_ be copied over to the destination just fine, but Speedcopy will raise an error.

The error remains even if I copy the file to another local folder, e.g. downloads and/or rename the file. E.g. here I copied the file from dropbox to my downloads folder (via Windows Explorer) and then tried to copy from there to our network share.

Error:
```python
# Error: File 'C:\\Users\\User\\Downloads\\sequence\\1001.exr' copy failed, error: The filename, directory name, or volume label syntax is incorrect.
# # Traceback (most recent call last):
# #   File "<maya console>", line 35, in <module>
# #   File "E:\openpype\OpenPype\.venv\lib\site-packages\speedcopy\__init__.py", line 300, in copyfile
# #     raise IOError(
# # OSError: File 'C:\\Users\\User\\Downloads\\sequence\\1001.exr' copy failed, error: The filename, directory name, or volume label syntax is incorrect.
```

The [error code](https://github.com/antirotor/speedcopy/blob/develop/speedcopy/__init__.py#L292) is `123`.

Copying the file manually via Explorer prompts me this:

![image](https://github.com/antirotor/speedcopy/assets/2439881/65bc1068-7284-4c4c-8abe-19f5a3946533)

Going through Powershell:

```powershell
PS C:\Users\User\Downloads\sequence> Get-Item .\1001.exr -Stream *


PSPath        : Microsoft.PowerShell.Core\FileSystem::C:\Users\User\Downloads\sequence\1001.exr::$DATA
PSParentPath  : Microsoft.PowerShell.Core\FileSystem::C:\Users\User\Downloads\sequence
PSChildName   : 1001.exr::$DATA
PSDrive       : C
PSProvider    : Microsoft.PowerShell.Core\FileSystem
PSIsContainer : False
FileName      : C:\Users\User\Downloads\sequence\1001.exr
Stream        : :$DATA
Length        : 56525612

PSPath        : Microsoft.PowerShell.Core\FileSystem::C:\Users\User\Downloads\sequence\1001.exr:com.dropbox.attrs
PSParentPath  : Microsoft.PowerShell.Core\FileSystem::C:\Users\User\Downloads\sequence
PSChildName   : 1001.exr:com.dropbox.attrs
PSDrive       : C
PSProvider    : Microsoft.PowerShell.Core\FileSystem
PSIsContainer : False
FileName      : C:\Users\User\Downloads\sequence\1001.exr
Stream        : com.dropbox.attrs
Length        : 26

```

Which indeed shows the `com.dropbox.attrs` data stream.

These are called "Alternate Data Streams" on "NTFS".

After removing the data stream:

```powershell
Remove-Item -Path .\1001.exr -Stream com.dropbox.attrs -Force -ErrorAction Silentlycontinue
```

The `speedcopy.copy_file` succeeds without error.
As such, it seems like the transfer fails due to properties that Dropbox ended up putting on the file.

Note: The source file system is NTFS - and that seems to be where Dropbox is putting extra properties onto the file, as also described [here](https://www.dropboxforum.com/t5/Apps-and-Installations/Problem-transferring-files-from-desktop-dropbox-folder-to-an/m-p/6462/highlight/true#M1067).

Maybe it could be worth adding support for a `SPEEDCOPY_IGNORE_ERROR_CODES` environment variable that could be set e.g. `123` or if there are others someone might want to ignore they could do `123,911`. But can't find ANY information about the error codes to this function myself, so I have no idea how valid `123` really is an error.

**Comment by BigRoy** [comment]
Even more, to ensure behavior _matches_ `shutil.copyfile` as close as possible we _should_ be ignoring the Alternate Data Stream. [`shutil` docs](https://docs.python.org/3/library/shutil.html) mentions:

> **Warning**
>
> Even the higher-level file copying functions ([shutil.copy()](https://docs.python.org/3/library/shutil.html#shutil.copy), [shutil.copy2()](https://docs.python.org/3/library/shutil.html#shutil.copy2)) cannot copy all file metadata.
>
> On POSIX platforms, this means that file owner and group are lost as well as ACLs. On Mac OS, the resource fork and other metadata are not used. This means that resources will be lost and file type and creator codes will not be correct. **On Windows, file owners, ACLs and alternate data streams are not copied.**

Additionally `shutil.copyfile` mentions it transfers without metadata to begin with.

**Comment by BigRoy** [comment]
We can pass the `COPY_FILE_SKIP_ALTERNATE_STREAMS` additional flag to `CopyFile2` it seems as the [third argument as the extended parameter struct](https://learn.microsoft.com/en-us/windows/win32/api/winbase/ns-winbase-copyfile2_extended_parameters).

**Comment by BigRoy** [comment]
It does transfer fine if indeed we pass `COPY_FILE_SKIP_ALTERNATE_STREAMS`


```python
import ctypes
from ctypes import wintypes

class COPYFILE2_EXTENDED_PARAMETERS(ctypes.Structure):
    """
    typedef struct COPYFILE2_EXTENDED_PARAMETERS {
      DWORD                       dwSize;
      DWORD                       dwCopyFlags;
      BOOL                        *pfCancel;
      PCOPYFILE2_PROGRESS_ROUTINE pProgressRoutine;
      PVOID                       pvCallbackContext;
    } COPYFILE2_EXTENDED_PARAMETERS;
    """

    _fields_ = [
        ("dwSize", wintypes.DWORD),
        ("dwCopyFlags", wintypes.DWORD),
        ("pfCancel", ctypes.POINTER(ctypes.c_bool)),
        ("pProgressRoutine", ctypes.WINFUNCTYPE(wintypes.BOOL, ctypes.c_int64, ctypes.c_int64, ctypes.c_void_p, ctypes.c_void_p)),
        ("pvCallbackContext", ctypes.c_void_p)
    ]



src = r"C:\Users\User\Downloads\sequence\hello.exr" 
dst = r"P:\1001.exr"

kernel32 = ctypes.WinDLL('kernel32', use_last_error=True, use_errno=True)
copyfile = kernel32.CopyFile2

copyfile.argtypes = (ctypes.c_wchar_p,
                     ctypes.c_wchar_p,
                     ctypes.POINTER(COPYFILE2_EXTENDED_PARAMETERS))
copyfile.restype = ctypes.HRESULT

source_file = os.path.abspath(os.path.normpath(src))
dest_file = os.path.abspath(os.path.normpath(dst))
if source_file.startswith('\\\\'):
    source_file = 'UNC\\' + source_file[2:]
if dest_file.startswith('\\\\'):
    dest_file = 'UNC\\' + dest_file[2:]

params = COPYFILE2_EXTENDED_PARAMETERS()
params.dwSize = ctypes.sizeof(COPYFILE2_EXTENDED_PARAMETERS)
params.dwCopyFlags = 0x00008000  # COPY_FILE_SKIP_ALTERNATE_STREAMS 
ret = copyfile('\\\\?\\' + source_file,
                '\\\\?\\' + dest_file, params)
                  
if ret == 0:
    error = ctypes.get_last_error()
    if error not in [0, 997]:
        raise IOError(
            "File {!r} copy failed, error: {}".format(
                src, ctypes.FormatError(error)))
```

---

The meaningful changes here are:

1. Defining the struct

```python

from ctypes import wintypes

class COPYFILE2_EXTENDED_PARAMETERS(ctypes.Structure):
    """
    typedef struct COPYFILE2_EXTENDED_PARAMETERS {
      DWORD                       dwSize;
      DWORD                       dwCopyFlags;
      BOOL                        *pfCancel;
      PCOPYFILE2_PROGRESS_ROUTINE pProgressRoutine;
      PVOID                       pvCallbackContext;
    } COPYFILE2_EXTENDED_PARAMETERS;
    """

    _fields_ = [
        ("dwSize", wintypes.DWORD),
        ("dwCopyFlags", wintypes.DWORD),
        ("pfCancel", ctypes.POINTER(ctypes.c_bool)),
        ("pProgressRoutine", ctypes.WINFUNCTYPE(wintypes.BOOL, ctypes.c_int64, ctypes.c_int64, ctypes.c_void_p, ctypes.c_void_p)),
        ("pvCallbackContext", ctypes.c_void_p)
    ]
```

Passing the parms as third argument to `copyfile`:
```python
params = COPYFILE2_EXTENDED_PARAMETERS()
params.dwSize = ctypes.sizeof(COPYFILE2_EXTENDED_PARAMETERS)
params.dwCopyFlags = 0x00008000  # COPY_FILE_SKIP_ALTERNATE_STREAMS
ret = copyfile('\\\\?\\' + source_file,
                '\\\\?\\' + dest_file, params)
```
